window.LISTA_MESTRA = [
    {"setor":"ADMIN-NOVO-ADM","nome":"ELISANGELA (JOINHA)","ramal":"8713"},
    {"setor":"ADMIN-NOVO-ADM","nome":"MARY JANE","ramal":"8413"},
    {"setor":"ADMIN-NOVO-ADM","nome":"SANDRO MELO","ramal":"8395"},
    {"setor":"ANALISTA-COMPRAS-CORP","nome":"GABRIELA LEMOS SOUTO MAIOR","ramal":"8682"},
    {"setor":"AUDITORIA-CORP","nome":"DANIELE SANTOS","ramal":"8487"},
    {"setor":"AUDITORIA-CORP","nome":"EMANUELE SILVA","ramal":"8619"},
    {"setor":"AUDITORIA-CORP","nome":"EMERSON CARDOSO","ramal":"8586"},
    {"setor":"AUDITORIA-CORP","nome":"GISELE MARINHO","ramal":"8619"},
    {"setor":"AUDITORIA-CORP","nome":"ISABELA FREITAS","ramal":"8619"},
    {"setor":"AUDITORIA-CORP","nome":"IZA LEILA","ramal":"8619"},
    {"setor":"AUDITORIA-CORP","nome":"JURANDIR PEREIRA","ramal":"8620"},
    {"setor":"AUDITORIA-CORP","nome":"TATIANE BANDEIRA","ramal":"8487"},
    {"setor":"CD-CABO","nome":"CD-CABO","ramal":"8364"},
    {"setor":"CD-CABO-FC","nome":"CD-CABO-FC","ramal":"8565 / 8364 / 8772"},
    {"setor":"CENTRAL","nome":"CADASTRO","ramal":"8766/ 8767"},
    {"setor":"CENTRAL","nome":"ENTRADA-NOTAS","ramal":"8548/ 8629/ 8426/ 8436"},
    {"setor":"CNR","nome":"GISELE","ramal":"8626/8544"},
    {"setor":"CNR","nome":"JANIELE","ramal":"8684"},
    {"setor":"COMERCIAL","nome":"ANNE KAROLINE","ramal":"8516"},
    {"setor":"COMERCIAL","nome":"LUCAS PAZ","ramal":"8357"},
    {"setor":"COMERCIAL","nome":"MONICA","ramal":"8319"},
    {"setor":"CONTABILIDADE","nome":"ANA PAULA","ramal":"8365"},
    {"setor":"CONTABILIDADE","nome":"CAROLINE PIMENTEL","ramal":"8615"},
    {"setor":"CONTABILIDADE","nome":"EDGELSON JUNIOR","ramal":"8575"},
    {"setor":"CONTABILIDADE","nome":"FERNANDA ALENCAR","ramal":"8575"},
    {"setor":"CONTABILIDADE","nome":"MARIANA BARBOSA","ramal":"8615"},
    {"setor":"CONTABILIDADE","nome":"MAURICIO VALENÇA","ramal":"8309"},
    {"setor":"CONTAS-A-PAGAR","nome":"CINTIA","ramal":"8534"},
    {"setor":"CONTAS-A-PAGAR","nome":"ERICA","ramal":"8369"},
    {"setor":"CONTAS-A-PAGAR","nome":"ILDA","ramal":"8509"},
    {"setor":"CONTROLADORIA","nome":"FABIANA","ramal":"8649"},
    {"setor":"CONTROLADORIA","nome":"MIRELLA","ramal":"8649"},
    {"setor":"CONTROLADORIA","nome":"TIAGO","ramal":"8405"},
    {"setor":"CONTROLADORIA","nome":"WILKER CUNHA","ramal":"8393"},
    {"setor":"COPA-COMERCIAL","nome":"COPA-COMERCIAL","ramal":"8400"},
    {"setor":"DP-CORP","nome":"CAMILA NASCIMENTO","ramal":"8312"},
    {"setor":"DP-CORP","nome":"EDINALDO VICTOR","ramal":"8579"},
    {"setor":"DP-CORP","nome":"EDITE GONÇALVES","ramal":"8418"},
    {"setor":"DP-CORP","nome":"ELIZIANE CORREIA","ramal":"8637"},
    {"setor":"DP-CORP","nome":"ELLEN BRASIL","ramal":"8514"},
    {"setor":"DP-CORP","nome":"JOYCE SALES","ramal":"8368"},
    {"setor":"DP-CORP","nome":"LOURDES MELO","ramal":"8582"},
    {"setor":"DP-CORP","nome":"MARCOS OLIVEIRA","ramal":"8654"},
    {"setor":"EXPANSÃO","nome":"CYNTHIA ALBURQUEQUE","ramal":"8551"},
    {"setor":"EXPANSÃO","nome":"FABIO RODRIGUES","ramal":"8410"},
    {"setor":"EXPANSÃO","nome":"JANDERSON","ramal":"8719"},
    {"setor":"EXPANSÃO","nome":"LUCIENE MARINHO","ramal":"8551"},
    {"setor":"EXPANSÃO","nome":"MATHEUS NASCIMENTO","ramal":"8611"},
    {"setor":"EXPANSÃO","nome":"SIMONE ROCHA","ramal":"8628"},
    {"setor":"EXPANSÃO","nome":"SITA RODRIGUES","ramal":"8719"},
    {"setor":"EXPANSÃO","nome":"THAIS DANIELE","ramal":"8410"},
    {"setor":"EXPANSÃO","nome":"TIAGO MELO","ramal":"8628"},
    {"setor":"FCX-LABS","nome":"LABS","ramal":"8732"},
    {"setor":"FINANCEIRO","nome":"DULCI","ramal":"8415"},
    {"setor":"FISCAL","nome":"ANSELMO TAVORA","ramal":"8365"},
    {"setor":"FISCAL","nome":"DANIELA MARIA","ramal":"8435"},
    {"setor":"FISCAL","nome":"EMILLY PEREIRA","ramal":"8636"},
    {"setor":"FISCAL","nome":"IGOR JESUS","ramal":"8539"},
    {"setor":"FISCAL","nome":"JUAN CESAR","ramal":"8575"},
    {"setor":"FISCAL","nome":"KELLWIR DIAS","ramal":"8636"},
    {"setor":"FISCAL","nome":"LILIAN VIEIRA","ramal":"8568"},
    {"setor":"FISCAL","nome":"ROBERTA LIMA","ramal":"8636"},
    {"setor":"FROTA","nome":"DANIEL AMORIM SOUZA","ramal":"-"},
    {"setor":"GUS","nome":"ELIANE","ramal":"8165"},
    {"setor":"INTEGRAÇÃO-ESTOQUES","nome":"CADASTRO","ramal":"8633/ 8519"},
    {"setor":"JAP","nome":"RENATO","ramal":"5022"},
    {"setor":"JURIDICO","nome":"EVELINE LINS","ramal":"8609"},
    {"setor":"JURIDICO","nome":"JULIANA FERNANDES","ramal":"8634"},
    {"setor":"JURIDICO","nome":"LEYLIANE BRAGA","ramal":"8634"},
    {"setor":"JURIDICO","nome":"LUANA CAROLINY","ramal":"8610"},
    {"setor":"JURIDICO","nome":"MARCELA COSTA","ramal":"8429"},
    {"setor":"JURIDICO","nome":"MARIA LARISSA","ramal":"8530"},
    {"setor":"JURIDICO","nome":"MELISSA FERREIRA","ramal":"8577"},
    {"setor":"LOJA-IMB","nome":"ACESSO BANHEIRO-PIAS-LOJA-IMB","ramal":"8466"},
    {"setor":"LOJA-IMB","nome":"AREA DE DESCANSO-LOJA-IMB","ramal":"8495"},
    {"setor":"LOJA-IMB","nome":"ASSISTÊNCIA TECNICA-LOJA-IMB","ramal":"8491"},
    {"setor":"LOJA-IMB","nome":"AUDITORIA-LOJA-IMB","ramal":"8378"},
    {"setor":"LOJA-IMB","nome":"AUTOCENTRO-LOJA-IMB","ramal":"8366"},
    {"setor":"LOJA-IMB","nome":"AUTOMOTIVO-LOJA-IMB","ramal":"8647"},
    {"setor":"LOJA-IMB","nome":"BALCÃO DE FERRAMENTAS-LOJA-IMB","ramal":"8467"},
    {"setor":"LOJA-IMB","nome":"BAR E RESTAURANTE-LOJA-IMB","ramal":"8498"},
    {"setor":"LOJA-IMB","nome":"BASICOS-LOJA-IMB","ramal":"8465"},
    {"setor":"LOJA-IMB","nome":"BRUNO-TI-LOJA-IMB","ramal":"8329"},
    {"setor":"LOJA-IMB","nome":"CAMEBA-LOJA-IMB","ramal":"8594"},
    {"setor":"LOJA-IMB","nome":"COBRANÇA-LOJA-IMB","ramal":"8331"},
    {"setor":"LOJA-IMB","nome":"CONEXÕES-LOJA-IMB","ramal":"8461"},
    {"setor":"LOJA-IMB","nome":"CONTABILIDADE-LOJA-IMB","ramal":"8413"},
    {"setor":"LOJA-IMB","nome":"CONTROLADORIA-LOJA-IMB","ramal":"8354"},
    {"setor":"LOJA-IMB","nome":"CREDIARIO-LOJA-IMB","ramal":"8336"},
    {"setor":"LOJA-IMB","nome":"DECORAÇÃO-MÓVEIS-LOJA-IMB","ramal":"8640"},
    {"setor":"LOJA-IMB","nome":"DEPOSITO-04-LOJA-IMB","ramal":"8493"},
    {"setor":"LOJA-IMB","nome":"DEPOSITO-05-LOJA-IMB","ramal":"8497"},
    {"setor":"LOJA-IMB","nome":"DEPOSITO-13-LOJA-IMB","ramal":"8471"},
    {"setor":"LOJA-IMB","nome":"DISTRIBUIÇÃO-01-LOJA-IMB","ramal":"8480"},
    {"setor":"LOJA-IMB","nome":"DISTRIBUIÇÃO-02-LOJA-IMB","ramal":"8482"},
    {"setor":"LOJA-IMB","nome":"DP-LOJA-IMB","ramal":"8714"},
    {"setor":"LOJA-IMB","nome":"E-COMMERCE-LOJA-IMB","ramal":"8683"},
    {"setor":"LOJA-IMB","nome":"ELETRICA-LOJA-IMB","ramal":"8648"},
    {"setor":"LOJA-IMB","nome":"ELETRODOMESTICO-LOJA-IMB","ramal":"8642"},
    {"setor":"LOJA-IMB","nome":"ENTRADA DE MERCADORIAS-LOJA-IMB","ramal":"8483 / 8481 / 8533"},
    {"setor":"LOJA-IMB","nome":"ENTREGAS-LOJA-IMB","ramal":"8348"},
    {"setor":"LOJA-IMB","nome":"ESCRITA FISCAL-LOJA-IMB","ramal":"8379"},
    {"setor":"LOJA-IMB","nome":"EVERALDO-LOJA-IMB","ramal":"8552"},
    {"setor":"LOJA-IMB","nome":"EXPEDIÇÃO-LOJA-IMB","ramal":"8489"},
    {"setor":"LOJA-IMB","nome":"FECHADURAS-LOJA-IMB","ramal":"8459"},
    {"setor":"LOJA-IMB","nome":"FRENTE-LOJA-IMB","ramal":"8431"},
    {"setor":"LOJA-IMB","nome":"GR-DEPOSITO-LOJA-IMB","ramal":"8478"},
    {"setor":"LOJA-IMB","nome":"GRS DE LOJA-IMB","ramal":"8370-8371"},
    {"setor":"LOJA-IMB","nome":"ILHA GERENCIAL-LOJA-IMB","ramal":"8473"},
    {"setor":"LOJA-IMB","nome":"JURIDICO-LOJA-IMB","ramal":"8530"},
    {"setor":"LOJA-IMB","nome":"LOJA DE SALDO-LOJA-IMB","ramal":"8506"},
    {"setor":"LOJA-IMB","nome":"LOUÇAS E MENTAIS-LOJA-IMB","ramal":"8451"},
    {"setor":"LOJA-IMB","nome":"LUSTRES E ILUMINARIAS-LOJA-IMB","ramal":"8648"},
    {"setor":"LOJA-IMB","nome":"MAQUINAS E MOTORES-LOJA-IMB","ramal":"8463"},
    {"setor":"LOJA-IMB","nome":"MARKETING-LOJA-IMB","ramal":"8310"},
    {"setor":"LOJA-IMB","nome":"OFICINA-LOJA-IMB","ramal":"8490"},
    {"setor":"LOJA-IMB","nome":"PISOS REVESTIMENTOS-LOJA-IMB","ramal":"8453"},
    {"setor":"LOJA-IMB","nome":"PORTAS E ESQUADRIAS-LOJA-IMB","ramal":"8459"},
    {"setor":"LOJA-IMB","nome":"RECEPÇÃO DE MERCADORIAS-LOJA-IMB","ramal":"8482"},
    {"setor":"LOJA-IMB","nome":"RH-LOJA-IMB","ramal":"8311"},
    {"setor":"LOJA-IMB","nome":"S.A.C-LOJA-IMB","ramal":"8390"},
    {"setor":"LOJA-IMB","nome":"SALA MEDICA-LOJA-IMB","ramal":"8464"},
    {"setor":"LOJA-IMB","nome":"TEC.SEGURANÇA TRABALHO-LOJA-IMB","ramal":"8497"},
    {"setor":"LOJA-IMB","nome":"TELEVENDAS-LOJA-IMB","ramal":"8380"},
    {"setor":"LOJA-IMB","nome":"TESOURARIA-LOJA-IMB","ramal":"8408"},
    {"setor":"LOJA-IMB","nome":"TINTAS-LOJA-IMB","ramal":"8472"},
    {"setor":"LOJA-IMB","nome":"TRANSFERÊNCIA-LOJA-IMB","ramal":"8580"},
    {"setor":"LOJA-IMB","nome":"TROCAS-LOJA-IMB","ramal":"8596"},
    {"setor":"LOJA-IMB","nome":"ULTILIDADES DOMESTICAS-LOJA-IMB","ramal":"8641"},
    {"setor":"LOJA-IMB","nome":"WELTON ADM-LOJA-IMB","ramal":"8354"},
    {"setor":"LOJA-TAM","nome":"MARIO","ramal":"1021"},
    {"setor":"LOJAS-IMB","nome":"CONTAS A PAGAR-LOJA-IMB","ramal":"8269"},
    {"setor":"MALL","nome":"ADRIANA SILVA","ramal":"8741"},
    {"setor":"MALL","nome":"CLAUDIA PATRICIA","ramal":"8441"},
    {"setor":"MALL","nome":"EMILY RAMOS","ramal":"8725/8520"},
    {"setor":"MALL","nome":"STHERFANNE CELINA","ramal":"8741"},
    {"setor":"MANUTENÇÃO","nome":"BRUNA SALES","ramal":"8612"},
    {"setor":"MANUTENÇÃO","nome":"EDUARDO COSTA","ramal":"8718"},
    {"setor":"MANUTENÇÃO","nome":"HANS FERREIRA","ramal":"8528"},
    {"setor":"MANUTENÇÃO","nome":"MELQUESEDEQUE DOMINGOS","ramal":"8618"},
    {"setor":"MANUTENÇÃO","nome":"RICARDO LIMA","ramal":"8612"},
    {"setor":"MANUTENÇÃO","nome":"STEPHAN STRATUSS","ramal":"8363"},
    {"setor":"OPERAÇÕES","nome":"BARBARA PIRES","ramal":"8519"},
    {"setor":"OPERAÇÕES","nome":"ESTEVES FERREIRA","ramal":"8510"},
    {"setor":"OPERAÇÕES","nome":"FELIPE ALVES","ramal":"8518"},
    {"setor":"OPERAÇÕES","nome":"INGRID SALES","ramal":"8518"},
    {"setor":"OPERAÇÕES","nome":"LAYANE","ramal":"8510"},
    {"setor":"OPERAÇÕES","nome":"LETICIA KATARINNA","ramal":"8518"},
    {"setor":"PREVENÇÃO DE PERDAS-IMB","nome":"ANDRE PONTES-DISTRITAL","ramal":"OBS"},
    {"setor":"PREVENÇÃO DE PERDAS-IMB","nome":"CANCELA DE VEICULOS -P9","ramal":"8396"},
    {"setor":"PREVENÇÃO DE PERDAS-IMB","nome":"MONITORAMENTO DE CAMERAS-CFTV","ramal":"8343"},
    {"setor":"PREVENÇÃO DE PERDAS-IMB","nome":"PORTARIA DE FUNCIONARIOS-P5","ramal":"8484"},
    {"setor":"PREVENÇÃO DE PERDAS-IMB","nome":"PORTARIA-NOVO-ADM","ramal":"8462"},
    {"setor":"PREVENÇÃO DE PERDAS-IMB","nome":"SALA DA GERÊNCIA-PREVENÇÃO","ramal":"8485"},
    {"setor":"PROJETOS-CORP","nome":"AMANDA CORREIA DANTAS","ramal":"8684"},
    {"setor":"PROJETOS-CORP","nome":"CASSANDRA ALVES","ramal":"8349"},
    {"setor":"PROJETOS-CORP","nome":"LOURDES","ramal":"8402"},
    {"setor":"PROJETOS-CORP","nome":"MARIA VITORIA ALVES DE OLIVEIRA","ramal":"8684"},
    {"setor":"PROJETOS-CORP","nome":"ROSEANE MONTEIRO","ramal":"8684"},
    {"setor":"RECEPÇÃO","nome":"ADM CORP","ramal":"8462"},
    {"setor":"RH-CORP","nome":"ANNA PAULA SOARES DOS SANTOS","ramal":"TEAMS"},
    {"setor":"RH-CORP","nome":"BARBARA BEATRIZ FERREIRA RAMOS","ramal":"8587"},
    {"setor":"RH-CORP","nome":"IEDA MACEDO","ramal":"8376"},
    {"setor":"RH-CORP","nome":"ISABELA MARANHÃO","ramal":"8583"},
    {"setor":"RH-CORP","nome":"KACIENE MILANEZ","ramal":"8587"},
    {"setor":"RH-CORP","nome":"LAURA FARIAS","ramal":"8587"},
    {"setor":"RH-CORP","nome":"LUDMILA MELO","ramal":"8586"},
    {"setor":"RH-CORP","nome":"MARILUCE SOARES","ramal":"8368"},
    {"setor":"RH-CORP","nome":"MICHELLE SOUZA","ramal":"8583"},
    {"setor":"RH-CORP","nome":"MYLENA BIONE","ramal":"8368"},
    {"setor":"RH-CORP","nome":"RENATA DIAS","ramal":"8368"},
    {"setor":"RH-CORP","nome":"SUMAYA CARVALHO","ramal":"8376"},
    {"setor":"RH-CORP","nome":"UILMA LIMA","ramal":"8584"},
    {"setor":"ROMANEIO","nome":"ROMANEIO","ramal":"8497"},
    {"setor":"TI","nome":"HAROLDO","ramal":"8532"},
    {"setor":"TI-INFRA","nome":"ALLESANDER CARVALHO","ramal":"8335"},
    {"setor":"TI-INFRA","nome":"ANTONNIELE SANTOS","ramal":"8730"},
    {"setor":"TI-INFRA","nome":"CLEBER","ramal":"8711"},
    {"setor":"TI-INFRA","nome":"ERICK OLIVEIRA","ramal":"8710"},
    {"setor":"TI-INFRA","nome":"ERLAN SIQUEIRA","ramal":"8557"},
    {"setor":"TI-INFRA","nome":"FELIPE BARROS","ramal":"8730"},
    {"setor":"TI-INFRA","nome":"RANIERI OLIVEIRA","ramal":"8711"},
    {"setor":"TI-INFRA","nome":"RODRIGO GAMA","ramal":"8557"},
    {"setor":"TI-INFRA","nome":"ROGERIO NUNES","ramal":"8557"},
    {"setor":"TI-PLANEJAMENTO","nome":"ALEXSANDRO HENRIQUE","ramal":"8524"},
    {"setor":"TI-PLANEJAMENTO","nome":"CARLOS GUIMARÃES","ramal":"8524"},
    {"setor":"TI-PLANEJAMENTO","nome":"GABRIELA HOLANDA","ramal":"8524"},
    {"setor":"TI-PLANEJAMENTO","nome":"LUIZ LIMA","ramal":"8524"},
    {"setor":"TI-PLANEJAMENTO","nome":"LUIZ TAVARES","ramal":"8524"},
    {"setor":"TI-PLANEJAMENTO","nome":"LUZANILTON CAMARA","ramal":"8524"},
    {"setor":"TI-PLANEJAMENTO","nome":"PEDRO VIEIRA","ramal":"8524"},
    {"setor":"TI-PLANEJAMENTO","nome":"SALVIO VIANA","ramal":"8520"},
    {"setor":"TI-PLANEJAMENTO","nome":"VINICIUS FRANÇA","ramal":"8524"},
    {"setor":"TI-SUPORT-TECH","nome":"ANTONIELLE LEONARDO SANTOS","ramal":"8730"},
    {"setor":"TI-SUPORT-TECH","nome":"DIEGO FREITAS","ramal":"8730"},
    {"setor":"TI-SUPORT-TECH","nome":"JOSE LUIZ DO MONTE GOMES","ramal":"8730"},
    {"setor":"TRANSPORTE","nome":"THIAGO JOSE SANTOS DA SILVA","ramal":"8439"},
    {"setor":"COMERCIAL-LOJA-IMB","nome":"MARCELO-COMPRADOR","ramal":"8324"},
    {"setor":"COMERCIAL-LOJA-IMB","nome":"SANDRA M.-COMPRADOR(A)","ramal":"8358"},
    {"setor":"COMERCIAL-LOJA-IMB","nome":"MORGANA-COMPRADOR(A)","ramal":"8442"},
    {"setor":"COMERCIAL-LOJA-IMB","nome":"MARCOS-COMPRADOR","ramal":"8346"},
    {"setor":"COMERCIAL-LOJA-IMB","nome":"AMANDA XAVIER-COMPRADOR(A)","ramal":"8353"},
    {"setor":"COMERCIAL-LOJA-IMB","nome":"ROSEANE-COMPRADOR(A)","ramal":"8347"},
    {"setor":"COMERCIAL-LOJA-IMB","nome":"IVAN-COMPRADOR","ramal":"8337"},
    {"setor":"COMERCIAL-LOJA-IMB","nome":"RÔMULO-COMPRADOR","ramal":"8337"},
    {"setor":"COMERCIAL-LOJA-IMB","nome":"RALF-COMPRADOR","ramal":"8323"},
    {"setor":"COMERCIAL-LOJA-IMB","nome":"EDUARDA-COMPRADOR(A)","ramal":"8318"},
    {"setor":"COMERCIAL-LOJA-IMB","nome":"CÉSAR-COMPRADOR","ramal":"8317"},
    {"setor":"COMERCIAL-LOJA-IMB","nome":"FERNANDO V.-COMPRADOR","ramal":"8425"},
    {"setor":"COMERCIAL-LOJA-IMB","nome":"RENATA NASCIMENTO-COMPRADOR(A)","ramal":"8440"},
    {"setor":"COMERCIAL-LOJA-IMB","nome":"LUCAS PAZ-COMPRADOR","ramal":"8357"},
    {"setor":"COMERCIAL-LOJA-IMB","nome":"INGRIDS-COMPRADOR(A)","ramal":"8325"},
    {"setor":"COMERCIAL-LOJA-IMB","nome":"SANDRA C.-COMPRADOR(A)","ramal":"8326"},
    {"setor":"COMERCIAL-LOJA-IMB","nome":"MATIAS-COMPRADOR","ramal":"8355"},
    {"setor":"COMERCIAL-LOJA-IMB","nome":"BRANDÃO-COMPRADOR","ramal":"8432"},
    {"setor":"COMRCIAL-LOJA-IMB","nome":"RICARDO F.-COMPRADOR","ramal":"8327"},
    {"setor":"COMECIAL-LOJA-IMB","nome":"THAISA-COMPRADOR(A)","ramal":"8328"},
    {"setor":"COMERCIAL-LOJA-IMB","nome":"RENATA P.-COMPRADOR(A)","ramal":"8437"},
    {"setor":"COMERCIAL-LOJA-IMB","nome":"KARINA-COMPRADOR(A)","ramal":"8420"},
    {"setor":"COMERCIAL-LOJA-IMB","nome":"ALANA-COMPRADOR(A)","ramal":"8443"},
    {"setor":"COMERCIAL-LOJA-IMB","nome":"BIANCA-COMPRADOR(A)","ramal":"8305"},
    {"setor":"COMERCIAL-LOJA-IMB","nome":"LIDIANE-COMPRADOR(A)","ramal":"8561"},
    {"setor":"COMERCIAL-LOJA-IMB","nome":"JACQUELINE C.-COMPRADOR(A)","ramal":"8313"},
    {"setor":"COMERCIAL-LOJA-IMB","nome":"CRISTIANE C.-COMPRADOR(A)","ramal":"8356"},
    {"setor":"COMERCIAL-LOJA-IMB","nome":"ISABELA OLIVEIRA-COMPRADOR(A)","ramal":"8447"},
    {"setor":"COMERCIAL-LOJA-IMB","nome":"IZABEL-IMPORTAÇÃO","ramal":"8445"},
    {"setor":"COMERCIAL-LOJA-IMB","nome":"ROBERTA-IMPORTAÇÃO","ramal":"8445"},
    {"setor":"COMERCIAL-LOJA-IMB","nome":"JOÃO VITOR-IMPORTAÇÃO","ramal":"8445"},
    {"setor":"COMERCIAL-","nome":"AUGUSTA-IMPORTAÇÃO","ramal":"8445"},
    {"setor":"OPERAÇÕES","nome":"FELIPE FREITAS","ramal":"81999891607"},
    {"setor":"CONTABILIDADE","nome":"LUIZ LIMA","ramal":"OBS"}
].map(item => ({ ...item, id: self.crypto.randomUUID() })); // Gera IDs únicos ao carregar